/**
 * Mock user for local development.
 * Mirrors the API user shape used by the app.
 */
export default function getTestUser() {
  return {
    id: '0f12ec83-fbd5-4e69-8452-f7af3116e570-374bdfe6-515b-48d9-bf0a-89a179e1b7a7',
    banner: {},
    calComAppointmentLink:
      'little-world/debug-stage-welcome?email=tim.timschupp%2B420%40gmail.com&hash=0f12ec83-fbd5-4e69-8452-f7af3116e570-374bdfe6-515b-48d9-bf0a-89a179e1b7a7&bookingcode=3e24d0ed-c3b3-4c33-9d64-f384318a04aa',
    email: 'tim.timschupp+420@gmail.com',
    emailVerified: true,
    forceMatchEligible: false,
    hadPreMatchingCall: false,
    hasMatch: false,
    hasRandomCallAccess: false,
    isSearching: false,
    isSupport: true,
    preMatchingAppointment: null,
    preMatchingCallJoinLink:
      'https://us06web.zoom.us/j/83369440498?pwd=bqE8ntbknsfErLgem8DemXN20bScp7.1',
    profile: {
      additional_interests: '',
      availability: {
        fr: ['16_18', '14_16', '12_14', '10_12', '18_20'],
        mo: ['10_12', '18_20'],
        sa: ['20_22', '18_20', '10_12'],
        su: ['10_12', '18_20', '20_22'],
        th: ['10_12', '12_14', '14_16', '16_18', '18_20', '20_22'],
        tu: ['12_14', '10_12', '08_10', '18_20'],
        we: ['16_18', '14_16', '10_12', '08_10', '18_20'],
      },
      avatar_config: {
        bgColor: '#9287FF',
        earSize: 'big',
        eyeBrowStyle: 'up',
        eyeStyle: 'oval',
        faceColor: '#ffdbac',
        glassesStyle: 'none',
        hairColor: '#000000',
        hairStyle: 'buzz',
        hatColor: '#A8A8A8',
        hatStyle: 'none',
        mouthStyle: 'laugh',
        noseStyle: 'short',
        sex: 'man',
        shirtColor: '#9287FF',
        shirtStyle: 'polo',
      },
      birth_year: 1999,
      country_of_residence: 'DE',
      description:
        "Hello everyone 👋🏼 \n\nIm the co-founder and CTO of little world. And as of today I'm your support match!\nWe are currently working hard to improve our matching process and give to offer you the best experience possible.\n\nFeel free to send me any question or suggestions.\n\nI'll take the time to answer all your messages but I might take a little time to do so. Tim",
      display_language: 'de',
      first_name: 'Tim',
      gender: 'female',
      image: null,
      image_type: 'avatar',
      interests: ['sociology', 'history', 'psycology', 'technology'],
      job_search: false,
      job_skill_description: '',
      lang_skill: [
        { lang: 'german', level: 'level-2' },
        { lang: 'spanish', level: 'level-1' },
        { lang: 'russian', level: 'level-1' },
      ],
      language_skill_description: '',
      liability_accepted: true,
      min_lang_level_partner: 'level-0',
      newsletter_subscribed: false,
      notify_channel: 'sms',
      other_target_group: 'Tourist',
      partner_gender: 'any',
      partner_location: 'anywhere',
      phone_mobile: '+491786828317',
      postal_code: '52064',
      push_notifications_enabled: false,
      second_name: 'Schupp',
      speech_medium: 'any',
      target_group: 'any',
      target_groups: ['refugee', 'any', 'worker'],
      user_type: 'learner',
    },
    status: { status: 'searching_no_match' },
    userFormCompleted: true,
  };
}
