name: Lint Check

on:
  pull_request:

concurrency:
  group: lint-check-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-check:
    name: lint check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          package_json_file: package.json

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: .nvmrc
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Run ESLint
        run: pnpm lint

      - name: Upload ESLint report
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: eslint-report
          path: eslint-report.log
